### ISSUE TITLE
如何做灰度

### ISSUE THREAD

**Issue by smallratluobin** [SpringCloud/spring-cloud-gray#10]
做灰度的流程是什么？

**Comment by saleson** [comment]
添加实例的灰度状态标签，然后添加灰度策略和决策，就可以了。

**Comment by txl75065** [comment]
完全不会用

**Comment by 734349414** [comment]
普通的http调用的接口，和rest接口，service-a和service-a1都能够支持吗？
还是只有service-b那种rest接口才支持灰度？

**Comment by saleson** [comment]
> 普通的http调用的接口，和rest接口，service-a和service-a1都能够支持吗？
> 还是只有service-b那种rest接口才支持灰度？

通过ribbon调用的，都能支持

**Comment by saleson** [comment]
已经添加使用手册，可以查看demo
