### ISSUE TITLE
rabbitmq一定需要配置么？

### ISSUE THREAD

**Issue by FlyingGlass** [SpringCloud/spring-cloud-gray#33]
如果仅需要灰度测试，rabbitmq是一定需要配置么？

**Comment by saleson** [comment]
可以不需， 把spring cloud stream相关的依赖包去掉就可以了。

**Comment by FlyingGlass** [comment]
好的，多谢!
请问有使用配置文档么？

**Comment by saleson** [comment]
正在写。。。 
如果有问题的话， 可以先加钉钉或微信沟通

**Comment by FlyingGlass** [comment]
好的，怎么添加作者微信或钉钉，或者有没有相应的群？

**Comment by saleson** [comment]
看readme 有钉钉群二维码
