### ISSUE TITLE
有具体的文档吗

### ISSUE THREAD

**Issue by df270464278** [SpringCloud/spring-cloud-gray#5]
这个项目有具体的文档吗,很多都是写在readme里面,感觉挺不方便的.还有项目的环境,所支持的spring cloud 版本,是必须项目指定的版本吗

**Comment by df270464278** [comment]
嗯，不发生很大的变化是没有问题，最主要的是项目中实现和继承的eureka里面的一些接口和类不发生变化。

**Comment by rbfw** [comment]
测试多版本时，运行eureka、server-a、server-b、zuul，4个服务，其中server-a启动了两个实例，版本分别为1和2，因为service-b调用service-a服务，我直接访问service-b接口地址http://192.168.1.60:10104/api/test/feignPost?version=1时，b是能正确调用到a对应的版本，但通过网关访问后，http://192.168.1.60:10301/gateway/service-b/api/test/feignPost?version=1，网关服务抛出如下异常：
```
{
    "timestamp": 1532951673001,
    "status": 500,
    "error": "Internal Server Error",
    "exception": "com.netflix.zuul.exception.ZuulException",
    "message": "GENERAL"
}
```
b服务本身没版本控制，敢问这是否是bug？还是我用的有问题？
联系邮箱：qiyang318@163.com

**Comment by saleson** [comment]
文档在更新中，更多的时间是在更新新的功能，所以文档更新会较慢。
另外该项目不指定springcloud 的具体版本，但目前支持spring cloud E版， 后面将会支持G版

**Comment by saleson** [comment]
已提供使用手册， 并且已经支持 spring cloud F版和G版
