### ISSUE TITLE
HttpTrackHeader策略下，异步调用feign client不起作用怎么办，是我哪里配置错了吗？

### ISSUE THREAD

**Issue by iolyak47** [SpringCloud/spring-cloud-gray#52]

**Comment by saleson** [comment]
如果是使用spring 管理的线程池执行异步可以添加配置参数 gray.client.threadpool.transparent-local-store.enabled = true;
其它的可以使用cn.springcloud.gray.concurrent.GrayConcurrentHelper中的静态方法包一下Runnable或Callable
