### ISSUE TITLE
开启gray.client.instance.grayEnroll=true后，启动报错

### ISSUE THREAD

**Issue by jiangwenqiang** [SpringCloud/spring-cloud-gray#56]
配置 开启gray.client.instance.grayEnroll=true后，GrayClientEnrollInitializingDestroyBean 依赖无法注入，服务启动失败。

**Comment by zyfjxust** [comment]
作者出来挨打，我也碰到了

**Comment by saleson** [comment]
失败信信贴出来看下

**Comment by saleson** [comment]
nacos向注册中心注册后没有得到自身的instanceId, 会抛出异常， 目前修复
