### ISSUE TITLE
spingCloud Finchley.RELEASE 版本，springboot: 2.0.4.RELEASE 版本使用 spring-cloud-starter-gray-server  B.0.0.6 版本报 ServiceDiscovery 找不到

### ISSUE THREAD

**Issue by chengmingwei** [SpringCloud/spring-cloud-gray#62]
> `Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-09-21 17:41:24.518 ERROR 16316 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field serviceDiscovery in cn.springcloud.gray.server.resources.rest.DiscoverInstanceResource required a bean of type 'cn.springcloud.gray.server.discovery.ServiceDiscovery' that could not be found.

Action:

Consider defining a bean of type 'cn.springcloud.gray.server.discovery.ServiceDiscovery' in your configuration.`

**Comment by javaerEric** [comment]
你是用的注册中心是什么，nacos？

**Comment by dinghung** [comment]
我也遇到了同样的问题，注册中心用的eureka

**Comment by dinghung** [comment]
<dependency>
            <groupId>cn.springcloud.gray</groupId>
            <artifactId>spring-cloud-gray-server-plugin-eureka</artifactId>
            <version>A.1.1.1</version>
        </dependency>
加上这个就好了

**Comment by saleson** [comment]
需要依赖spring-cloud-gray的服务发现插件
