### ISSUE TITLE
grayFeignClient 配置上去后循环依赖

### ISSUE THREAD

**Issue by zyfjxust** [SpringCloud/spring-cloud-gray#63]
项目加上这个配置后,
@EnableFeignClients(defaultConfiguration = {GrayFeignClientsConfiguration.class})

启动不了,报错,循环依赖
![image](https://user-images.githubusercontent.com/10087025/94000870-55078a00-fdca-11ea-905a-e0e90bb0c51c.png)

期待得到你回复,紧急

**Comment by saleson** [comment]
cn.springcloud.gray.client.netflix.feign.configuration.GrayFeignAutoConfiguration 类中已经自动加上@EnableFeignClients(defaultConfiguration = {GrayFeignClientsConfiguration.class})， 在应用项目中不再需要显示的添加这段代码了。

**Comment by zyfjxust** [comment]
我在自定义feignclient的配置项增加了一个LoadBalancerFeignClient bean,这个bean才是真正工作的client,也是构成grayFeignClient的构造函数的参数.我的spring.cloud.版本是 2.0.9.release. 然后当前的版本是  1.5.22.RELEASE.  我猜原因是低版本会默认实现一个  LoadBlacerFeignClient, 而高一点的版本因为自定义了一个client,就不会默认加载真正工作的LoadBlacerFeignClient.  这个bean的缺失导致grayFeignClient无法完成构造实例,陷入循环依赖的陷阱.
