### ISSUE TITLE
通过网关访问b服务，带上版本号出现异常

### ISSUE THREAD

**Issue by rbfw** [SpringCloud/spring-cloud-gray#7]
测试多版本时，运行eureka、server-a、server-b、zuul，4个服务，其中server-a启动了两个实例，版本分别为1和2，因为service-b调用service-a服务，我直接访问service-b接口地址http://192.168.1.60:10104/api/test/feignPost?version=1时，b是能正确调用到a对应的版本，但通过网关访问后，http://192.168.1.60:10301/gateway/service-b/api/test/feignPost?version=1，网关服务抛出如下异常：
```
{
    "timestamp": 1532951673001,
    "status": 500,
    "error": "Internal Server Error",
    "exception": "com.netflix.zuul.exception.ZuulException",
    "message": "GENERAL"
}
```
b服务本身没版本控制，敢问这是否是bug？还是我用的有问题？
联系邮箱：qiyang318@163.com

**Comment by SoftwareKing** [comment]
@rbfw 加我微信Software_King,进微信群处理

**Comment by SoftwareKing** [comment]
done
